version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "<APP_NAME>"
          ContainerPort: <SERVICE_PORT>
        CapacityProviderStrategy:
          - CapacityProvider: test
            Base: 0
            Weight: 1
